pinry/core/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from tastypie.api import Api

from .api import ImageResource, ThumbnailResource, PinResource, UserResource, RawquerylogResource,BlogResource
from .views import CreateImage


v1_api = Api(api_name='v1')
v1_api.register(ImageResource())
v1_api.register(ThumbnailResource())
v1_api.register(PinResource())
v1_api.register(UserResource())
v1_api.register(RawquerylogResource())
v1_api.register(BlogResource())


urlpatterns = patterns('',
    url(r'^api/', include(v1_api.urls, namespace='api')),

    url(r'^pins/pin-form/$', TemplateView.as_view(template_name='core/pin_form.html'),
        name='pin-form'),
    url(r'^pins/create-image/$', CreateImage.as_view(), name='create-image'),

    url(r'^pins/tag/(?P<tag>(\w|-)+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='tag-pins'),
    url(r'^pins/user/(?P<user>(\w|-)+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='user-pins'),
    url(r'^$', TemplateView.as_view(template_name='core/pins.html'),
        name='recent-pins'),
    

)

pinry/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'', include('pinry.core.urls', namespace='core')),
                       url(r'', include('pinry.users.urls', namespace='users')),
                       url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
                       url(r'^admin/', include(admin.site.urls)),
                       )
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT,
                                }),
                            )

pinry/users/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from .views import CreateUser
from pinry.core.models import Rawquerylog

urlpatterns = patterns('',
    url(r'^private/$', 'pinry.users.views.private', name='private'),
    url(r'^register/$', CreateUser.as_view(), name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', 'pinry.users.views.logout_user', name='logout'),
    url(r'^profile/$','pinry.users.views.profile',name='profile'),
    url(r'^profile/querysession/delete/(\d+)/$','pinry.users.views.delete_querysession'),
)

pinry/users/models.py
import hashlib

from django.contrib.auth.models import User as BaseUser


class User(BaseUser):
    @property
    def gravatar(self):
        return hashlib.md5(self.email).hexdigest()

    class Meta:
        proxy = True

pinry/core/forms.py
from django import forms

from django_images.models import Image


FIELD_NAME_MAPPING = {
    'image': 'qqfile',
}


class ImageForm(forms.ModelForm):
    def add_prefix(self, field_name):
        field_name = FIELD_NAME_MAPPING.get(field_name, field_name)
        return super(ImageForm, self).add_prefix(field_name)

    class Meta:
        model = Image
        fields = ('image',)

pinry/users/forms.py
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.models import User


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username,
    email, and password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
    }
    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w-]+$')
    password = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

pinry/core/views.py
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import CreateView
from django_images.models import Image

from braces.views import JSONResponseMixin, LoginRequiredMixin
from django_images.models import Thumbnail

from .forms import ImageForm


class CreateImage(JSONResponseMixin, LoginRequiredMixin, CreateView):
    template_name = None  # JavaScript-only view
    model = Image
    form_class = ImageForm

    def get(self, request, *args, **kwargs):
        if not request.is_ajax():
            return HttpResponseRedirect(reverse('core:recent-pins'))
        return super(CreateImage, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        image = form.save()
        for size in settings.IMAGE_SIZES.keys():
            Thumbnail.objects.get_or_create_at_size(image.pk, size)
        return self.render_json_response({
            'success': {
                'id': image.id
            }
        })

    def form_invalid(self, form):
        return self.render_json_response({'error': form.errors})

pinry/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission,Group
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.template import Context,loader
from django.utils.functional import lazy
from django.views.generic import CreateView

from .forms import UserCreationForm
from pinry.users.models import User
from pinry.core.models import Rawquerylog,Userquerysession,Querysessiondetail,Query,Webpageurl

from django.shortcuts import render

reverse_lazy = lambda name=None, *args: lazy(reverse, str)(name, args=args)


class CreateUser(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('core:recent-pins')

    def get(self, request, *args, **kwargs):
        if not settings.ALLOW_NEW_REGISTRATIONS:
            messages.error(request, "The admin of this service is not allowing new registrations.")
            return HttpResponseRedirect(reverse('core:recent-pins'))
        return super(CreateUser, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        redirect = super(CreateUser, self).form_valid(form)
        group = Group.objects.get(name = 'default')
        permissions = Permission.objects.filter(codename__in=['add_pin', 'add_image','core'])

        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])
        user.user_permissions = permissions
        user.groups = [group]
        login(self.request, user)
        return redirect


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('core:recent-pins'))


def private(request):
    return TemplateResponse(request, 'users/private.html', None)

def delete_querysession(request, id):
   query_session_obj = Userquerysession.objects.get(pk = id)
   query_session_obj.delete()
   return HttpResponseRedirect('/profile/')


def profile(request):
    user_id = request.user.pk
    
    query_session_metas=Userquerysession.objects.filter(submitter_id = user_id).order_by('-created_time')
    query_sessions = []

    for item in query_session_metas:

        details = Querysessiondetail.objects.filter(querysession = item.id,iscompleted = True).order_by('timestamp')
        if details.exists():
            #check if result exists
            query_session = {}
            query_session['meta'] = item
            query_session['details'] = details

            query_sessions.append(query_session)
    
    # keyword_ids = Querysessiondetail.objects.filter(submitter = user_id ).values_list('query',flat = True).distinct()
    # keyword_dict = Query.objects.filter(id__in = keyword_ids)
    # keywords = {}
    # for item in keyword_dict:
    #     keywords[item.id] = item.keyword

    # pageurl_ids = Querysessiondetail.objects.filter(submitter = user_id ).values_list('url_id',flat = True).distinct()
    # pageurl_dict = Webpageurl.objects.filter(id__in = pageurl_ids)
    # pageurls = {}
    # for item in pageurl_dict:
    #     keywords[item.id] = {'url':item.url, 'query_id':item.query_id}

    rawquery = Rawquerylog.objects.filter(submitter = user_id)
    
    context = {'query_sessions':query_sessions ,'raw':rawquery}



    return render(request,'users/profile.html',context)

pinry/templates/base.html
{% load static from staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

        <!--  ___                     ___           ___                 
             /  /\      ___          /__/\         /  /\          ___   
            /  /::\    /  /\         \  \:\       /  /::\        /__/|  
           /  /:/\:\  /  /:/          \  \:\     /  /:/\:\      |  |:|  
          /  /:/~/:/ /__/::\      _____\__\:\   /  /:/~/:/      |  |:|  
         /__/:/ /:/  \__\/\:\__  /__/::::::::\ /__/:/ /:/___  __|__|:|  
         \  \:\/:/      \  \:\/\ \  \:\~~\~~\/ \  \:\/:::::/ /__/::::\  
          \  \::/        \__\::/  \  \:\  ~~~   \  \::/~~~~     ~\~~\:\ 
           \  \:\        /__/:/    \  \:\        \  \:\           \  \:\
            \  \:\       \__\/      \  \:\        \  \:\           \__\/
             \__\/                   \__\/         \__\/             -->

        <title>{% block title %}{{ SITE_NAME }}{% endblock %}</title>

        <!-- CSS -->
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Monoton"/>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.0/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/file-uploader/3.1.1/fineuploader.css"/>
        {% compress css %}
        <link rel="stylesheet" href="{% static "css/messages.css" %}"/>
        <link rel="stylesheet" href="{% static "css/lightbox.css" %}"/>
        <link rel="stylesheet" href="{% static "css/pinry.css" %}"/>
        {%  endcompress %}
        {% compress css inline %}
        {% block extra_css %}{% endblock %}
        {% endcompress %}
        <!-- End CSS -->

        <!-- Start JavaScript Variables -->
        <script>
        var apiLimitPerPage = {{ API_LIMIT_PER_PAGE }},
            errors = {% if not messages %}null,{% else %}[
                {% for message in messages %}{
                    tags: "{{ message.tags }}",
                    text: "{{ message }}"
                }{% endfor %}
            ],{% endif %}
            currentUser = {
                id: "{{ user.id }}",
                username: "{{ user.username }}",
                gravatar: "{{ user.gravatar }}"
            },
            tagFilter = "{{ request.resolver_match.kwargs.tag }}",
            userFilter = "{{ request.resolver_match.kwargs.user }}";
        </script>
        <!-- End JavaScript Variables -->
    </head>

    <body>
        <!-- Navigation -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <a href="{% url 'core:recent-pins' %}" class="brand pull-left">{{ SITE_NAME }}</a>
                <ul class="nav pull-right">
                {% if user.is_authenticated %}
		     <li><a href="profile/">Personal Profile</a></li>
                    <li>{% include "includes/bookmarklet_link.html" %}</li>
                    <li><a onclick="pinForm()">New Pin</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}
                </ul>
            </div>
        </div>
        <!-- End Navigation -->

        <!-- Messages -->
        <ul id="messages"></ul>
        <!-- End Messages -->

        <!-- No Script -->
        <div id="noscript">
            <noscript>Scripting is not enabled in your browser, if you are using
                a plugin like NoScript *high five*! Our code is open source and
                you can view it on
                <a href="https://github.com/pinry/pinry/">GitHub</a>.
                <style>.spinner{display:none;}</style></noscript>
        </div>
        <!-- End No Script -->

        <!-- Content -->
        {% block yield %}{% endblock %}
	{% block profile %}{% endblock %}
        <!-- End Content -->

        <!-- Templates -->
        {% include "includes/messages.html" %}
        {% include "includes/lightbox.html" %}
        {% include "includes/pins.html" %}
        {% include "includes/pin_form.html" %}
        {% block extra_templates %}{% endblock %}
        <!-- End Templates -->

        <!-- JavaScript -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.0.0-rc.3/handlebars.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/file-uploader/3.1.1/jquery.fineuploader.min.js"></script>
        {% compress js %}
        <script src="{% static "js/helpers.js" %}"></script>
        <script src="{% static "js/messages.js" %}"></script>
        <script src="{% static "js/lightbox.js" %}"></script>
        <script src="{% static "js/pinry.js" %}"></script>
        <script src="{% static "js/pin-form.js" %}"></script>
        {% endcompress %}
        {% compress js inline %}
        {% block extra_js %}{% endblock %}
        {% endcompress %}
        <!-- End JavaScript -->
    </body>
</html>